const capabilities = [
  { title: 'Frontend and architecture', summary: 'Scalable application foundations for complex enterprise and consumer products.', skills: ['React', 'Next.js', 'TypeScript', 'JavaScript ES6+', 'SPA', 'SSR', 'ISR', 'Micro-frontends', 'Component systems'] },
  { title: 'AI and data systems', summary: 'Intuitive experiences that translate complex AI capabilities into useful workflows.', skills: ['LLM-integrated UX', 'RAG-style search', 'Chat interfaces', 'Agent workflows', 'ML-driven UI', 'Explainable AI'] },
  { title: 'Data and state', summary: 'Reliable client-server coordination for asynchronous and data-intensive products.', skills: ['React Query', 'Server state', 'Client state', 'Caching', 'Request deduplication'] },
  { title: 'Observability and tooling', summary: 'Development and production feedback loops that improve delivery and reliability.', skills: ['Sentry', 'Datadog', 'Webpack', 'Vite', 'Chrome DevTools'] },
  { title: 'Performance and rendering', summary: 'Responsive experiences across high-volume datasets and complex interactions.', skills: ['Core Web Vitals', 'Virtualization', 'Progressive hydration', 'Streaming UI', 'Rendering optimization'] },
  { title: 'Backend and APIs', summary: 'Supporting services and contracts for integrated product experiences.', skills: ['Node.js', 'Python', 'REST APIs', 'GraphQL'] },
  { title: 'Infrastructure', summary: 'Cloud and delivery patterns supporting scalable, performant applications.', skills: ['AWS EC2 / S3 / Lambda', 'Edge architecture', 'CDN optimization', 'Docker', 'CI/CD'] },
]

export default function Skills() {
  return <section className="page-section" aria-labelledby="skills-title"><div className="section-shell"><div className="page-intro"><p className="eyebrow">Capabilities</p><h1 id="skills-title">Architecture, AI experiences, and performance at scale.</h1><p>I specialize in frontend systems for large datasets, LLM-integrated workflows, real-time products, and the engineering practices needed to operate them reliably.</p></div><div className="mt-16 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{capabilities.map((capability, index) => <article key={capability.title} className="content-card"><span className="font-mono text-xs text-cyan-300">{String(index + 1).padStart(2, '0')}</span><h2 className="mt-5 text-xl font-semibold text-white">{capability.title}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-slate-400">{capability.summary}</p><ul className="mt-6 flex flex-wrap gap-2">{capability.skills.map((skill) => <li key={skill} className="tech-pill">{skill}</li>)}</ul></article>)}</div></div></section>
}
