const capabilities = [
  { title: 'Frontend engineering', summary: 'Modern, accessible application architecture for enterprise and consumer products.', skills: ['React', 'Next.js', 'TypeScript', 'JavaScript ES6+', 'HTML5', 'CSS3', 'SSR / ISR', 'WCAG', 'Design systems', 'Micro-frontends'] },
  { title: 'State and data architecture', summary: 'Reliable client and server state across asynchronous and real-time workflows.', skills: ['TanStack Query', 'Client state', 'Server state', 'Caching strategies', 'Data fetching', 'Real-time synchronization'] },
  { title: 'AI-powered experiences', summary: 'Intuitive interfaces connecting users with intelligent product capabilities.', skills: ['LLM integration', 'AI assistants', 'Semantic search', 'Streaming responses', 'Structured AI output', 'Prompt engineering'] },
  { title: 'Performance and rendering', summary: 'Fast interaction and visualization across high-volume, data-intensive products.', skills: ['Core Web Vitals', 'Virtualization', 'Code splitting', 'Lazy loading', 'Progressive hydration', 'Streaming UI', 'Large datasets'] },
  { title: 'Testing and quality', summary: 'Automated feedback loops supporting confident and sustainable delivery.', skills: ['Jest', 'React Testing Library', 'Playwright', 'Cypress', 'Unit testing', 'Integration testing', 'E2E testing'] },
  { title: 'Tooling and developer experience', summary: 'Consistent development environments and maintainable component workflows.', skills: ['Webpack', 'Vite', 'Babel', 'ESLint', 'Prettier', 'Storybook', 'Chrome DevTools', 'npm / Yarn / pnpm'] },
  { title: 'Backend and APIs', summary: 'Pragmatic services and interfaces supporting distributed product systems.', skills: ['Node.js', 'Python', 'REST APIs', 'GraphQL', 'API design', 'Distributed systems'] },
  { title: 'Cloud and infrastructure', summary: 'Delivery and runtime patterns for reliable web applications at scale.', skills: ['AWS EC2 / S3 / Lambda', 'CDN optimization', 'Edge architecture', 'Docker', 'CI/CD', 'Cloud deployment'] },
]

export default function Skills() {
  return <section className="page-section" aria-labelledby="skills-title"><div className="section-shell"><div className="page-intro"><p className="eyebrow">Capabilities</p><h1 id="skills-title">Frontend depth for products that demand more.</h1><p>I specialize in React architecture, performance, real-time interfaces, AI-powered product experiences, and the engineering practices needed to deliver them reliably.</p></div><div className="mt-16 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{capabilities.map((capability, index) => <article key={capability.title} className="content-card"><span className="font-mono text-xs text-cyan-300">{String(index + 1).padStart(2, '0')}</span><h2 className="mt-5 text-xl font-semibold text-white">{capability.title}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-slate-400">{capability.summary}</p><ul className="mt-6 flex flex-wrap gap-2">{capability.skills.map((skill) => <li key={skill} className="tech-pill">{skill}</li>)}</ul></article>)}</div></div></section>
}
